apiVersion: db2.example.com/v1
kind: DB2Cluster
metadata:
  name: db2
spec:
  # TODO(user): Add fields here
  Size: 3
  EtcdEndpoint: "10.109.75.82:2379"
  DBName: "HADRDB"
  DBInstance: "db2inst1"
  DBInstancePassword: "db2inst1"
  StorageClassforHADR: "managed-nfs-storage"
  StorageClassforDB: "openebs-hostpath"
